[package]
name = "docs_rs_builder"
version = "0.6.0"
authors = ["Onur Aslan <onuraslan@gmail.com>", "The Rust Project Developers"]
license = "MIT"
repository = "https://github.com/rust-lang/docs.rs"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
docs_rs_build_limits = { path = "../../lib/docs_rs_build_limits" }
docs_rs_build_queue = { path = "../../lib/docs_rs_build_queue" }
docs_rs_cargo_metadata = { path = "../../lib/docs_rs_cargo_metadata" }
docs_rs_config = { path = "../../lib/docs_rs_config" }
docs_rs_context = { path = "../../lib/docs_rs_context" }
docs_rs_database = { path = "../../lib/docs_rs_database" }
docs_rs_env_vars = { path = "../../lib/docs_rs_env_vars" }
docs_rs_fastly = { path = "../../lib/docs_rs_fastly" }
docs_rs_logging = { path = "../../lib/docs_rs_logging" }
docs_rs_opentelemetry = { path = "../../lib/docs_rs_opentelemetry" }
docs_rs_registry_api = { path = "../../lib/docs_rs_registry_api" }
docs_rs_repository_stats = { path = "../../lib/docs_rs_repository_stats" }
docs_rs_rustdoc_json = { path = "../../lib/docs_rs_rustdoc_json" }
docs_rs_storage = { path = "../../lib/docs_rs_storage" }
docs_rs_types = { path = "../../lib/docs_rs_types" }
docs_rs_utils = { path = "../../lib/docs_rs_utils" }
docsrs-metadata = { path = "../../lib/metadata" }
log = "0.4"
opentelemetry = { workspace = true }
regex = { workspace = true }
rustwide = { version = "0.22.0", features = ["unstable-toolchain-ci", "unstable"] }
serde_json = { workspace = true }
sqlx = { workspace = true }
sysinfo = { version = "0.38.0", default-features = false, features = ["system"] }
tempfile = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-log = "0.2.0"

[dev-dependencies]
docs_rs_build_queue = { path = "../../lib/docs_rs_build_queue", features = ["testing"] }
docs_rs_config = { path = "../../lib/docs_rs_config", features = ["testing"] }
docs_rs_context = { path = "../../lib/docs_rs_context", features = ["testing"] }
docs_rs_database = { path = "../../lib/docs_rs_database", features = ["testing"] }
docs_rs_fastly = { path = "../../lib/docs_rs_fastly", features = ["testing"] }
docs_rs_headers = { path = "../../lib/docs_rs_headers", features = ["testing"] }
docs_rs_storage = { path = "../../lib/docs_rs_storage", features = ["testing"] }
docs_rs_types = { path = "../../lib/docs_rs_types", features = ["testing"] }
docs_rs_utils = { path = "../../lib/docs_rs_utils", features = ["testing"] }
pretty_assertions = { workspace = true }
test-case = { workspace = true }
