[package]
name = "docs_rs_builder"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
docs_rs_build_queue = { path = "../../lib/docs_rs_build_queue" }
docs_rs_build_utils = { path = "../../lib/docs_rs_build_utils" }
docs_rs_fastly = { path = "../../lib/docs_rs_fastly" }
docs_rs_cargo_metadata = { path = "../../lib/docs_rs_cargo_metadata" }
docs_rs_context = { path = "../../lib/docs_rs_context" }
docs_rs_database = { path = "../../lib/docs_rs_database" }
docs_rs_env_vars = { path = "../../lib/docs_rs_env_vars" }
docs_rs_logging = { path = "../../lib/docs_rs_logging" }
docs_rs_opentelemetry = { path = "../../lib/docs_rs_opentelemetry" }
docs_rs_registry_api = { path = "../../lib/docs_rs_registry_api" }
docs_rs_repository_stats = { path = "../../lib/docs_rs_repository_stats" }
docs_rs_storage = { path = "../../lib/docs_rs_storage" }
docs_rs_utils = { path = "../../lib/docs_rs_utils" }
docsrs-metadata = { path = "../../lib/metadata" }
futures-util = { workspace = true }
hostname = "0.4.0"
itertools = { workspace = true }
log = "0.4"
opentelemetry = { workspace = true }
regex = { workspace = true }
rustwide = { version = "0.20.0", features = ["unstable-toolchain-ci", "unstable"] }
serde = { workspace = true }
serde_json = { workspace = true }
slug = { workspace = true }
sqlx = { workspace = true }
sysinfo = { version = "0.37.2", default-features = false, features = ["system"] }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-log = "0.2.0"

