[package]
name = "docs_rs_watcher"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
# NOTE: on the new infra, switch back from `git-https-reqwest` to `git-https` (curl) once the curl version is new enough
crates-index = { version = "3.0.0", default-features = false, features = ["git", "git-https-reqwest", "git-performance", "parallel"] }
# NOTE: on the new infra, switch back from `http-reqwest` to `http-curl` once the curl version is new enough
crates-index-diff = { version = "29.0.0", default-features = false, features = [ "max-performance", "semver", "http-reqwest" ] }
docs_rs_build_queue = { path = "../../lib/docs_rs_build_queue" }
docs_rs_config = { path = "../../lib/docs_rs_config" }
docs_rs_context = { path = "../../lib/docs_rs_context" }
docs_rs_database = { path = "../../lib/docs_rs_database" }
docs_rs_env_vars = { path = "../../lib/docs_rs_env_vars" }
docs_rs_fastly = { path = "../../lib/docs_rs_fastly" }
docs_rs_logging = { path = "../../lib/docs_rs_logging" }
docs_rs_opentelemetry = { path = "../../lib/docs_rs_opentelemetry" }
docs_rs_repository_stats = { path = "../../lib/docs_rs_repository_stats" }
docs_rs_storage = { path = "../../lib/docs_rs_storage" }
docs_rs_types = { path = "../../lib/docs_rs_types" }
docs_rs_utils = { path = "../../lib/docs_rs_utils" }
futures-util = { workspace = true }
itertools = { workspace = true }
opentelemetry = { workspace = true }
rayon = "1.6.1"
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
docs_rs_config = { path = "../../lib/docs_rs_config", features = ["testing"] }
docs_rs_context = { path = "../../lib/docs_rs_context", features = ["testing"] }
docs_rs_database = { path = "../../lib/docs_rs_database", features = ["testing"] }
docs_rs_fastly = { path = "../../lib/docs_rs_fastly", features = ["testing"] }
docs_rs_rustdoc_json = { path = "../../lib/docs_rs_rustdoc_json" }
docs_rs_storage = { path = "../../lib/docs_rs_storage", features = ["testing"] }
docs_rs_test_fakes = { path = "../../lib/docs_rs_test_fakes" }
docs_rs_types = { path = "../../lib/docs_rs_types", features = ["testing"] }
pretty_assertions = { workspace = true }
test-case = { workspace = true }
