[package]
name = "docs_rs_watcher"
version = "0.6.0"
authors = ["Onur Aslan <onuraslan@gmail.com>", "The Rust Project Developers"]
license = "MIT"
repository = "https://github.com/rust-lang/docs.rs"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
crates-index = { version = "3.0.0", default-features = false, features = ["git", "git-https", "git-performance", "parallel"] }
crates-index-diff = { version = "29.0.0", features = [ "max-performance" ]}
docs_rs_build_queue = { path = "../../lib/docs_rs_build_queue" }
docs_rs_context = { path = "../../lib/docs_rs_context" }
docs_rs_database = { path = "../../lib/docs_rs_database" }
docs_rs_env_vars = { path = "../../lib/docs_rs_env_vars" }
docs_rs_fastly = { path = "../../lib/docs_rs_fastly" }
docs_rs_logging = { path = "../../lib/docs_rs_logging" }
docs_rs_opentelemetry = { path = "../../lib/docs_rs_opentelemetry" }
docs_rs_repository_stats = { path = "../../lib/docs_rs_repository_stats" }
docs_rs_storage = { path = "../../lib/docs_rs_storage" }
docs_rs_types = { path = "../../lib/docs_rs_types" }
docs_rs_utils = { path = "../../lib/docs_rs_utils" }
futures-util = { workspace = true }
itertools = { workspace = true }
opentelemetry = { workspace = true }
rayon = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
docs_rs_database = { path = "../../lib/docs_rs_database", features = ["testing"] }
docs_rs_fastly = { path = "../../lib/docs_rs_fastly", features = ["testing"] }
docs_rs_rustdoc_json = { path = "../../lib/docs_rs_rustdoc_json" }
docs_rs_storage = { path = "../../lib/docs_rs_storage", features = ["testing"] }
docs_rs_test_fakes = { path = "../../lib/docs_rs_test_fakes" }
docs_rs_types = { path = "../../lib/docs_rs_types", features = ["testing"] }
pretty_assertions = { workspace = true }
test-case = { workspace = true }
