[package]
name = "badge"
version = "0.3.0"
description = "Simple badge generator"
authors = ["Onur Aslan <onur@onur.im>", "Joshua Nelson <jyn514@gmail.com>", "Chase Wilson <contact@chasewilson.dev>", "The Rust Project Developers"]
license-file = "LICENSE"
repository = "https://github.com/rust-lang/docs.rs"
documentation = "https://docs.rs/badge"
edition = "2018"

[dependencies]
base64 = "0.12"
rusttype = "0.9"
once_cell = "1"
