[package]
name = "badge"
version = "0.1.1"
description = "Simple badge generator"
authors = ["Onur Aslan <onur@onur.im>"]
license-file = "LICENSE"
repository = "https://github.com/onur/docs.rs"
documentation = "https://docs.rs/badge"

[lib]
path = "badge.rs"

[dependencies]
rusttype = "0.4.0"
