[package]
name = "cratesfyi"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
docs_rs_builder = { path = "../docs_rs_builder" }
docs_rs_config = { path = "../../lib/docs_rs_config" }
docs_rs_context = { path = "../../lib/docs_rs_context" }
docs_rs_logging = { path = "../../lib/docs_rs_logging" }
docs_rs_utils = { path = "../../lib/docs_rs_utils" }
docs_rs_watcher = { path = "../docs_rs_watcher" }
docs_rs_web = { path = "../docs_rs_web" }
tokio = { workspace = true }
tracing = { workspace = true }
